/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Scene');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.Transform');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Scene = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Scene, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Scene.displayName = 'proto.Scene';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Scene.prototype.toObject = function(opt_includeInstance) {
  return proto.Scene.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Scene} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Scene.toObject = function(includeInstance, msg) {
  var f, obj = {
    xform: (f = msg.getXform()) && proto.Transform.toObject(includeInstance, f),
    patternId: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Scene}
 */
proto.Scene.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Scene;
  return proto.Scene.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Scene} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Scene}
 */
proto.Scene.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Transform;
      reader.readMessage(value,proto.Transform.deserializeBinaryFromReader);
      msg.setXform(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPatternId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Scene.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Scene.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Scene} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Scene.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getXform();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Transform.serializeBinaryToWriter
    );
  }
  f = message.getPatternId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional Transform xform = 1;
 * @return {?proto.Transform}
 */
proto.Scene.prototype.getXform = function() {
  return /** @type{?proto.Transform} */ (
    jspb.Message.getWrapperField(this, proto.Transform, 1));
};


/** @param {?proto.Transform|undefined} value */
proto.Scene.prototype.setXform = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Scene.prototype.clearXform = function() {
  this.setXform(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Scene.prototype.hasXform = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 pattern_id = 2;
 * @return {number}
 */
proto.Scene.prototype.getPatternId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Scene.prototype.setPatternId = function(value) {
  jspb.Message.setField(this, 2, value);
};


